[tool.poetry]
name = "twitter_clone"
version = "0.1.0"
description = ""
authors = ["Rochelle Edwards <rochellelynn.programmer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.5"
django-crispy-forms = "^1.12.0"
python-dotenv = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
